package modelpreset

const (
	DisplayNameProviderAnthropic       = "Anthropic"
	DisplayNameProviderGoogleGemini    = "Google Gemini API"
	DisplayNameProviderHuggingFace     = "Hugging Face"
	DisplayNameProviderLlamaCPP        = "llama.cpp"
	DisplayNameProviderLMStudio        = "LM Studio"
	DisplayNameProviderLocalAI         = "LocalAI"
	DisplayNameProviderMistral         = "Mistral AI"
	DisplayNameProviderOllama          = "Ollama"
	DisplayNameProviderOpenAIChat      = "OpenAI Chat Completions API"
	DisplayNameProviderOpenAIResponses = "OpenAI Responses API"
	DisplayNameProviderOpenRouter      = "OpenRouter"
	DisplayNameProviderSGLang          = "SGLang"
	DisplayNameProviderVLLM            = "vLLM"
	DisplayNameProviderXAI             = "xAI"
)

const (
	DisplayNameGPT41     = "GPT 4.1"
	DisplayNameGPT41Mini = "GPT 4.1 Mini"
	DisplayNameGPT4o     = "GPT 4o"
	DisplayNameGPT4oMini = "GPT 4o Mini"

	DisplayNameGPT55         = "GPT 5.5"
	DisplayNameGPT54         = "GPT 5.4"
	DisplayNameGPT54Mini     = "GPT 5.4 Mini"
	DisplayNameGPT54Nano     = "GPT 5.4 Nano"
	DisplayNameGPT53Codex    = "GPT 5.3 Codex"
	DisplayNameGPT52         = "GPT 5.2"
	DisplayNameGPT52Codex    = "GPT 5.2 Codex"
	DisplayNameGPT51         = "GPT 5.1"
	DisplayNameGPT51Codex    = "GPT 5.1 Codex"
	DisplayNameGPT51CodexMax = "GPT 5.1 Codex Max"
	DisplayNameGPT5Mini      = "GPT 5 Mini"

	DisplayNameClaudeFable5   = "Claude Fable 5"
	DisplayNameClaudeOpus48   = "Claude Opus 4.8"
	DisplayNameClaudeOpus47   = "Claude Opus 4.7"
	DisplayNameClaudeOpus46   = "Claude Opus 4.6"
	DisplayNameClaudeOpus45   = "Claude Opus 4.5"
	DisplayNameClaudeOpus41   = "Claude Opus 4.1"
	DisplayNameClaudeSonnet5  = "Claude Sonnet 5"
	DisplayNameClaudeSonnet46 = "Claude Sonnet 4.6"
	DisplayNameClaudeSonnet45 = "Claude Sonnet 4.5"
	DisplayNameClaudeSonnet4  = "Claude Sonnet 4"
	DisplayNameClaudeHaiku45  = "Claude Haiku 4.5"

	DisplayNameGemini31Pro       = "Gemini 3.1 Pro"
	DisplayNameGemini35Flash     = "Gemini 3.5 Flash"
	DisplayNameGemini3Flash      = "Gemini 3 Flash"
	DisplayNameGemini31FlashLite = "Gemini 3.1 Flash Lite"
	DisplayNameGemini25Flash     = "Gemini 2.5 Flash"
	DisplayNameGemini25FlashLite = "Gemini 2.5 Flash Lite"

	DisplayNameMistralMedium35 = "Mistral Medium 3.5"
	DisplayNameMistralSmall4   = "Mistral Small 4"
	DisplayNameMistralLarge3   = "Mistral Large 3"
	DisplayNameDevstral2       = "Devstral 2"

	DisplayNameGrok43             = "Grok 4.3"
	DisplayNameBuild01            = "Build 0.1"
	DisplayNameGrok42Reasoning    = "Grok 4.2 Reasoning"
	DisplayNameGrok42NonReasoning = "Grok 4.2 Non-Reasoning"
)

const (
	DisplayNameGPTOSS120B = "gpt-oss 120B"
	DisplayNameGPTOSS20B  = "gpt-oss 20B"

	DisplayNameLlama4Behemoth = "Llama 4 Behemoth"
	DisplayNameLlama4Maverick = "Llama 4 Maverick"
	DisplayNameLlama4Scout    = "Llama 4 Scout"

	DisplayNameGemma426BA4B = "Gemma 4 26B A4B"
	DisplayNameGemma426B    = "Gemma 4 26B"
	DisplayNameGemma4E4B    = "Gemma 4 E4B"

	DisplayNameQwen3635BA3B         = "Qwen3.6 35B A3B"
	DisplayNameQwen3635B            = "Qwen3.6 35B"
	DisplayNameQwen3627B            = "Qwen3.6 27B"
	DisplayNameQwen37Max            = "Qwen3.7 Max"
	DisplayNameQwen37Plus           = "Qwen3.7 Plus"
	DisplayNameQwen3VL30BA3B        = "Qwen3-VL 30B A3B"
	DisplayNameQwen3VL30B           = "Qwen3-VL 30B"
	DisplayNameQwen3Coder30B        = "Qwen3-Coder 30B"
	DisplayNameQwen3Coder30BA3B     = "Qwen3-Coder 30B A3B"
	DisplayNameQwen3CoderNext       = "Qwen3-Coder Next"
	DisplayNameDeepSeekR18B         = "DeepSeek-R1 8B"
	DisplayNameDeepSeekV4Flash      = "DeepSeek V4 Flash"
	DisplayNameDeepSeekV4Pro        = "DeepSeek V4 Pro"
	DisplayNameMinistral314B        = "Ministral 3 14B"
	DisplayNameGLM47Flash30BA3B     = "GLM-4.7 Flash 30B A3B"
	DisplayNameGLM47                = "GLM 4.7"
	DisplayNameGLM5                 = "GLM 5"
	DisplayNameGLM51                = "GLM 5.1"
	DisplayNameGLM51FP8             = "GLM 5.1 FP8"
	DisplayNameGLM52                = "GLM 5.2"
	DisplayNameGLM52FP8             = "GLM 5.2 FP8"
	DisplayNameZAIGLM51             = "Z.AI GLM 5.1"
	DisplayNameZAIGLM52             = "Z.AI GLM 5.2"
	DisplayNamePhi4Reasoning14B     = "Phi-4 Reasoning 14B"
	DisplayNameDevstral224B         = "Devstral Small 2 24B"
	DisplayNameOrnith1035BFP8       = "Ornith 1.0 35B FP8"
	DisplayNameMiMoV2Flash          = "MiMo V2 Flash"
	DisplayNameMiMoV25Pro           = "MiMo V2.5 Pro"
	DisplayNameXiaomiMiMoV25        = "Xiaomi MiMo V2.5"
	DisplayNameXiaomiMiMoV25Pro     = "Xiaomi MiMo V2.5 Pro"
	DisplayNameMiniMaxM25           = "MiniMax M2.5"
	DisplayNameMiniMaxM25Free       = "MiniMax M2.5 Free"
	DisplayNameMiniMaxM27           = "MiniMax M2.7"
	DisplayNameMiniMaxM3            = "MiniMax M3"
	DisplayNameKimiK2Thinking       = "Kimi K2 Thinking"
	DisplayNameKimiK2Instruct       = "Kimi K2 Instruct"
	DisplayNameKimiK2Instruct0905   = "Kimi K2 Instruct 0905"
	DisplayNameMoonshotKimiK26      = "MoonshotAI Kimi K2.6"
	DisplayNameMoonshotKimiK27Code  = "MoonshotAI Kimi K2.7 Code"
	DisplayNameStep35Flash          = "Step 3.5 Flash"
	DisplayNameStep37Flash          = "Step 3.7 Flash"
	DisplayNameTencentHy3Preview    = "Tencent Hy3 Preview"
	DisplayNamePoolsideLagunaM1Free = "Poolside Laguna M.1 Free"

	DisplayNameNemotron3UltraNVFP4 = "NVIDIA Nemotron 3 Ultra 550B A55B NVFP4"
	DisplayNameNemotron3UltraBF16  = "NVIDIA Nemotron 3 Ultra 550B A55B BF16"
	DisplayNameNemotron3SuperBF16  = "NVIDIA Nemotron 3 Super 120B A12B BF16"
	DisplayNameNemotron3UltraFree  = "NVIDIA Nemotron 3 Ultra Free"
	DisplayNameNemotron3SuperFree  = "NVIDIA Nemotron 3 Super Free"
)

const (
	DisplayNameGPTOSS120BFireworksAI = "gpt-oss 120B (Fireworks AI)"
	DisplayNameGPTOSS20BFireworksAI  = "gpt-oss 20B (Fireworks AI)"

	DisplayNameQwen3Coder30BA3BFireworksAI    = "Qwen3-Coder 30B A3B (Fireworks AI)"
	DisplayNameGLM52FireworksAI               = "GLM 5.2 (Fireworks AI)"
	DisplayNameDeepSeekV4FlashFireworksAI     = "DeepSeek V4 Flash (Fireworks AI)"
	DisplayNameDeepSeekV4ProFireworksAI       = "DeepSeek V4 Pro (Fireworks AI)"
	DisplayNameNemotron3UltraNVFP4FireworksAI = "NVIDIA Nemotron 3 Ultra 550B A55B NVFP4 (Fireworks AI)"
	DisplayNameGLM51FireworksAI               = "GLM 5.1 (Fireworks AI)"
	DisplayNameMiniMaxM27FireworksAI          = "MiniMax M2.7 (Fireworks AI)"
	DisplayNameGLM51FP8FireworksAI            = "GLM 5.1 FP8 (Fireworks AI)"

	DisplayNameOrnith1035BFP8DeepInfra     = "Ornith 1.0 35B FP8 (DeepInfra)"
	DisplayNameMiMoV25ProDeepInfra         = "MiMo V2.5 Pro (DeepInfra)"
	DisplayNameNemotron3UltraBF16DeepInfra = "NVIDIA Nemotron 3 Ultra 550B A55B BF16 (DeepInfra)"

	DisplayNameGLM52FP8ZAI = "GLM 5.2 FP8 (Z.AI)"

	DisplayNameQwen3CoderNextNovita     = "Qwen3-Coder Next (Novita)"
	DisplayNameGLM5Novita               = "GLM 5 (Novita)"
	DisplayNameMiniMaxM25Novita         = "MiniMax M2.5 (Novita)"
	DisplayNameKimiK2InstructNovita     = "Kimi K2 Instruct (Novita)"
	DisplayNameKimiK2Instruct0905Novita = "Kimi K2 Instruct 0905 (Novita)"

	DisplayNameNemotron3SuperBF16FeatherlessAI = "NVIDIA Nemotron 3 Super 120B A12B BF16 (Featherless AI)"
	DisplayNameKimiK2ThinkingFeatherlessAI     = "Kimi K2 Thinking (Featherless AI)"
	DisplayNameStep35FlashFeatherlessAI        = "Step 3.5 Flash (Featherless AI)"
	DisplayNameMiMoV2FlashFeatherlessAI        = "MiMo V2 Flash (Featherless AI)"

	DisplayNameGLM47Cerebras = "GLM 4.7 (Cerebras)"
)
