package modelpreset

const (
	PresetGPT56Sol   ModelPresetID = "gpt56sol"
	PresetGPT56Terra ModelPresetID = "gpt56terra"
	PresetGPT56Luna  ModelPresetID = "gpt56luna"

	PresetGPT55 ModelPresetID = "gpt55"

	PresetGPT54     ModelPresetID = "gpt54"
	PresetGPT54Mini ModelPresetID = "gpt54mini"
	PresetGPT54Nano ModelPresetID = "gpt54nano"

	PresetGPT53Codex ModelPresetID = "gpt53Codex"

	PresetGPT52         ModelPresetID = "gpt52"
	PresetGPT52Codex    ModelPresetID = "gpt52Codex"
	PresetGPT51         ModelPresetID = "gpt51"
	PresetGPT51Codex    ModelPresetID = "gpt51Codex"
	PresetGPT51CodexMax ModelPresetID = "gpt51CodexMax"

	PresetGPT41     ModelPresetID = "gpt41"
	PresetGPT41Mini ModelPresetID = "gpt41Mini"
	PresetGPT4o     ModelPresetID = "gpt4o"
	PresetGPT4oMini ModelPresetID = "gpt4oMini"

	PresetGPT5Mini ModelPresetID = "gpt5Mini"

	PresetClaudeFable5   ModelPresetID = "fable5"
	PresetClaudeOpus48   ModelPresetID = "opus48"
	PresetClaudeOpus47   ModelPresetID = "opus47"
	PresetClaudeOpus46   ModelPresetID = "opus46"
	PresetClaudeOpus45   ModelPresetID = "opus45"
	PresetClaudeOpus41   ModelPresetID = "opus41"
	PresetClaudeSonnet5  ModelPresetID = "sonnet5"
	PresetClaudeSonnet46 ModelPresetID = "sonnet46"
	PresetClaudeSonnet45 ModelPresetID = "sonnet45"
	PresetClaudeSonnet4  ModelPresetID = "sonnet4"
	PresetClaudeHaiku45  ModelPresetID = "haiku45"

	PresetGemini36Flash     ModelPresetID = "gemini36Flash"
	PresetGemini35Flash     ModelPresetID = "gemini35Flash"
	PresetGemini35FlashLite ModelPresetID = "gemini35FlashLite"
	PresetGemini31Pro       ModelPresetID = "gemini31Pro"
	PresetGemini31FlashLite ModelPresetID = "gemini31FlashLite"
	PresetGemini3Flash      ModelPresetID = "gemini3Flash"
	PresetGemini25Flash     ModelPresetID = "gemini25Flash"
	PresetGemini25FlashLite ModelPresetID = "gemini25FlashLite"

	PresetMistralMedium35 ModelPresetID = "mistralMedium35"
	PresetMistralSmall4   ModelPresetID = "mistralSmall4"
	PresetMistralLarge3   ModelPresetID = "mistralLarge3"
	PresetDevstral2       ModelPresetID = "devstral2"

	PresetGrok45             ModelPresetID = "grok45"
	PresetGrok43             ModelPresetID = "grok43"
	PresetBuild01            ModelPresetID = "grokBuild01"
	PresetGrok42Reasoning    ModelPresetID = "grok42Reasoning"
	PresetGrok42NonReasoning ModelPresetID = "grok42NonReasoning"
)

const (
	PresetGPTOSS120B ModelPresetID = "gptoss120b"
	PresetGPTOSS20B  ModelPresetID = "gptoss20b"

	PresetLlama4Behemoth ModelPresetID = "llama4Behemoth"
	PresetLlama4Maverick ModelPresetID = "llama4Maverick"
	PresetLlama4Scout    ModelPresetID = "llama4Scout"

	PresetGemma426BA4B ModelPresetID = "gemma426ba4b"
	PresetGemma426B    ModelPresetID = "gemma426b"
	PresetGemma4E4B    ModelPresetID = "gemma4e4b"

	PresetQwen3635BA3B         ModelPresetID = "qwen3635ba3b"
	PresetQwen3635B            ModelPresetID = "qwen3635b"
	PresetQwen3627B            ModelPresetID = "qwen3627b"
	PresetQwen37Max            ModelPresetID = "qwen37Max"
	PresetQwen37Plus           ModelPresetID = "qwen37Plus"
	PresetQwen3VL30BA3B        ModelPresetID = "qwen3vl30ba3b"
	PresetQwen3VL30B           ModelPresetID = "qwen3vl30b"
	PresetQwen3Coder30B        ModelPresetID = "qwen3coder30b"
	PresetQwen3Coder30BA3B     ModelPresetID = "qwen3coder30ba3b"
	PresetQwen3CoderNext       ModelPresetID = "qwen3codernext"
	PresetDeepSeekR18B         ModelPresetID = "deepseekr18b"
	PresetDeepSeekV4Flash      ModelPresetID = "deepseekv4flash"
	PresetDeepSeekV4Pro        ModelPresetID = "deepseekv4pro"
	PresetMinistral314B        ModelPresetID = "ministral314b"
	PresetGLM47Flash30BA3B     ModelPresetID = "glm47flash30ba3b"
	PresetGLM47                ModelPresetID = "glm47"
	PresetGLM5                 ModelPresetID = "glm5"
	PresetGLM51                ModelPresetID = "glm51"
	PresetGLM51FP8             ModelPresetID = "glm51fp8"
	PresetGLM52                ModelPresetID = "glm52"
	PresetGLM52FP8             ModelPresetID = "glm52fp8"
	PresetZAIGLM51             ModelPresetID = "zaiglm51"
	PresetZAIGLM52             ModelPresetID = "zaiglm52"
	PresetPhi4Reasoning14B     ModelPresetID = "phi4reasoning14b"
	PresetDevstral224B         ModelPresetID = "devstral224b"
	PresetOrnith1035BFP8       ModelPresetID = "ornith1035bfp8"
	PresetMiMoV2Flash          ModelPresetID = "mimov2flash"
	PresetMiMoV25Pro           ModelPresetID = "mimov25pro"
	PresetXiaomiMiMoV25        ModelPresetID = "xiaomiMiMoV25"
	PresetXiaomiMiMoV25Pro     ModelPresetID = "xiaomiMiMoV25Pro"
	PresetMiniMaxM25           ModelPresetID = "minimaxm25"
	PresetMiniMaxM25Free       ModelPresetID = "minimaxm25free"
	PresetMiniMaxM27           ModelPresetID = "minimaxm27"
	PresetMiniMaxM3            ModelPresetID = "minimaxM3"
	PresetKimiK2Thinking       ModelPresetID = "kimik2thinking"
	PresetKimiK2Instruct       ModelPresetID = "kimik2instruct"
	PresetKimiK2Instruct0905   ModelPresetID = "kimik2instruct0905"
	PresetMoonshotKimiK26      ModelPresetID = "moonshotKimiK26"
	PresetMoonshotKimiK27Code  ModelPresetID = "moonshotKimiK27Code"
	PresetStep35Flash          ModelPresetID = "step35flash"
	PresetStep37Flash          ModelPresetID = "step37Flash"
	PresetTencentHy3Preview    ModelPresetID = "tencentHy3Preview"
	PresetPoolsideLagunaM1Free ModelPresetID = "poolsideLagunaM1Free"

	PresetNemotron3UltraNVFP4 ModelPresetID = "nemotron3ultraNVFP4"
	PresetNemotron3UltraBF16  ModelPresetID = "nemotron3ultraBF16"
	PresetNemotron3SuperBF16  ModelPresetID = "nemotron3superBF16"
	PresetNemotron3UltraFree  ModelPresetID = "nvidiaNemotron3UltraFree"
	PresetNemotron3SuperFree  ModelPresetID = "nvidiaNemotron3SuperFree"
)

const (
	PresetGPTOSS120BFireworksAI ModelPresetID = "gptoss120bFireworksAI"
	PresetGPTOSS20BFireworksAI  ModelPresetID = "gptoss20bFireworksAI"

	PresetQwen3Coder30BA3BFireworksAI    ModelPresetID = "qwen3coder30ba3bFireworksAI"
	PresetGLM52FireworksAI               ModelPresetID = "glm52FireworksAI"
	PresetDeepSeekV4FlashFireworksAI     ModelPresetID = "deepseekv4flashFireworksAI"
	PresetDeepSeekV4ProFireworksAI       ModelPresetID = "deepseekv4proFireworksAI"
	PresetNemotron3UltraNVFP4FireworksAI ModelPresetID = "nemotron3ultraNVFP4FireworksAI"
	PresetGLM51FireworksAI               ModelPresetID = "glm51FireworksAI"
	PresetMiniMaxM27FireworksAI          ModelPresetID = "minimaxm27FireworksAI"
	PresetGLM51FP8FireworksAI            ModelPresetID = "glm51fp8FireworksAI"

	PresetOrnith1035BFP8DeepInfra     ModelPresetID = "ornith1035bfp8DeepInfra"
	PresetMiMoV25ProDeepInfra         ModelPresetID = "mimov25proDeepInfra"
	PresetNemotron3UltraBF16DeepInfra ModelPresetID = "nemotron3ultraBF16DeepInfra"

	PresetGLM52FP8ZAI ModelPresetID = "glm52fp8ZAI"

	PresetQwen3CoderNextNovita     ModelPresetID = "qwen3codernextNovita"
	PresetGLM5Novita               ModelPresetID = "glm5Novita"
	PresetMiniMaxM25Novita         ModelPresetID = "minimaxm25Novita"
	PresetKimiK2InstructNovita     ModelPresetID = "kimik2instructNovita"
	PresetKimiK2Instruct0905Novita ModelPresetID = "kimik2instruct0905Novita"

	PresetNemotron3SuperBF16FeatherlessAI ModelPresetID = "nemotron3superBF16FeatherlessAI"
	PresetKimiK2ThinkingFeatherlessAI     ModelPresetID = "kimik2thinkingFeatherlessAI"
	PresetStep35FlashFeatherlessAI        ModelPresetID = "step35flashFeatherlessAI"
	PresetMiMoV2FlashFeatherlessAI        ModelPresetID = "mimov2flashFeatherlessAI"

	PresetGLM47Cerebras ModelPresetID = "glm47Cerebras"
)
